import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PayPalProvider from "@/components/PayPalProvider"; // ✅ PayPal 설정을 클라이언트 컴포넌트로 분리

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PayPalProvider> {/* ✅ PayPal 설정을 클라이언트 컴포넌트에서 처리 */}
          {children}
        </PayPalProvider>
      </body>
    </html>
  );
}
